name: vyos lts build

on:
  workflow_dispatch:

env:
  LTS_VERSION: 1.4.0-epa2

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: git clone vyos-build
        run: git clone -b sagitta --single-branch https://github.com/vyos/vyos-build

      - name: set vyos version
        working-directory: ./vyos-build
        run: echo "VYOS_VERSION=${{ env.LTS_VERSION }}-lts-$(git log -n 1 --format='format:%h' ${{ env.LTS_VERSION }})" >> $GITHUB_ENV

      - name: checkout git tag
        working-directory: ./vyos-build
        run: git checkout ${{ env.LTS_VERSION }} && git switch -c ${{ env.LTS_VERSION }}

      - name: build vyos iso
        working-directory: ./vyos-build
        run: |
          docker run --rm -it --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:sagitta bash -c "sudo make clean && sudo ./build-vyos-image iso --architecture amd64 --build-by 'owo@chesskuo.tw' --build-type release --version '${{ env.VYOS_VERSION }}'"
          ls -al build/

      - name: copy vyos iso
        run: cp ./vyos-build/build/live-image-amd64.hybrid.iso ./vyos-${{ env.VYOS_VERSION }}-amd64.iso

      - name: Upload release file
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VYOS_VERSION }}
          fail_on_unmatched_files: true
          files: |
            ./vyos-${{ env.VYOS_VERSION }}-amd64.iso
